### ISSUE TITLE
file save does not work

### ISSUE THREAD

**Issue by moetiker** [Zimbra-Community/seafile#2]
hi

o view seafile files and creating a folder does work
o upload a file does not work. it uploads the file with no error but it never get
 stored on the seafile server

**Comment by ghost** [comment]
In Seafile you can only create folders at the root level, no files (upload). This is by design, you need to upload to a sub folder.

Unfortunately ATM I cannot provide a solution or error message, as that would require a permanent fork from the WebDAV Client code.

**Comment by moetiker** [comment]
Sorry bud thats what I did. Upload a file to a subfolder of a Library. Is there a log file I could debug what is going wrong.

**Comment by ghost** [comment]
Can you show your installation output from the terminal, and the user configuration settings. Aka where you configured your seafile server. 



Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by moetiker** [comment]
sorry but the installation console output is gone... I did not keep that....

In the zimbra trace_log I have the following entry during upload.

`13:38:39.649:qtp1231156911-7256://zimbra.domain.ch/service/extension/dav_upload/?path=/filedav/Daten%20Archiv%20Manuel/test1/ REQUEST 192.168.0.159 POST __zlcmid=tYiQZLQuucy6jk; ZM_TRUST_TOKEN=0_f806811f842adeba55b4d39f189dfb46044dffd5_7469643d394a3135343933353730373b; ZM_TEST=true; ZM_LOGIN_CSRF=889d1975-fde0-48bc-88a8-221c64d9eb1c; ZM_AUTH_TOKEN=0_6b70ca58da61de3588a9aab5f4eac1e378064f9e_69643d33363a37323637646238612d633734622d3434616763d313a333b747970653d363a7a696d6272613b753d313a613b7469643d31303a313032343433373334393b76657273696f6e3d31343a382e382e31355f47415f333832393b637372663d313a313b; JSESSIONID=node0lbj1tbe5gcqh14ofepeojucqu2.node0; Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
13:38:39.792:qtp1231156911-7256://zimbra.domain.ch/service/extension/dav_upload/?path=/filedav/Daten%20Archiv%20Manuel/test1/ RESPONSE 200 null
13:38:39.793:qtp1231156911-7294 CLOSED HttpConnection@dc634db::SocketChannelEndPoint@25a8da2b{/192.168.0.159:42434<->/192.168.0.159:8080,CLOSED,fill=-,flush=-,to=1/60000}{io=0/0,kio=-1,kro=-1}->HttpConnection@dc634db[p=HttpParser{s=CLOSED,16867 of 16867},g=HttpGenerator@43a0fc17{s=START}]=>HttpChannelOverHttp@429b00a6{r=1,c=false,c=false/false,a=IDLE,uri=null,age=0}
`
![2019-09-04-13-36](https://user-images.githubusercontent.com/631883/64251506-ffd7ac80-cf18-11e9-9be5-242ef2081058.png)

on the seafile server I have the following ngnix proxy log:

`
10.10.99.82 - manuel@domain.ch [04/Sep/2019:13:48:50 +0200] "PROPFIND /filedav/Daten%20Archiv%20Manuel/test1/ HTTP/1.1" 207 485 "-" "Sardine/UNAVAILABLE"
10.10.99.82 - manuel@domain.ch [04/Sep/2019:13:48:50 +0200] "PROPFIND /filedav/Daten%20Archiv%20Manuel/test1/ HTTP/1.1" 207 485 "-" "Sardine/UNAVAILABLE"
10.10.99.82 - - [04/Sep/2019:13:48:54 +0200] "POST /seafhttp/repo/head-commits-multi/ HTTP/1.1" 200 575 "-" "Seafile/7.0.2 (Linux)"
10.10.99.82 - manuel@domain.ch [04/Sep/2019:13:48:54 +0200] "PUT /filedav/Daten%20Archiv%20Manuel/test1/20190904-130839%20OP%2043801%20Re%20public%20key.eml HTTP/1.1" 401 142 "-" "Java/11.0.2"
`
