### ISSUE TITLE
"Go to SeaFile" button does not work 

### ISSUE THREAD

**Issue by moetiker** [Zimbra-Community/seafile#3]
Hi 

The Button goes to server does not work and popup a error . 
![2019-09-04-15-06](https://user-images.githubusercontent.com/631883/64257371-898d7700-cf25-11e9-85b4-f25bc916e6ba.png)

the error message shows in plaintext username and password I think that's not good

```
method: | [unknown]
-- | --
msg: | unknown document: OCS
code: | service.UNKNOWN_DOCUMENT
detail: | soap:Sender
trace: | qtp1231156911-8476:1567602199161:586a740b14e00730
request: | <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Header><context xmlns="urn:zimbra"><userAgent name="ZimbraWebClient - GC76 (Linux)" version="8.8.15_GA_3847"/><session id="1438"/><notify seq="781"/><account by="name">cccc@domain.ch</account><format type="js"/><csrfToken>0_edc44501ac2013c37b6ff982ac1dca3c882c5f3c</csrfToken></context></soap:Header><soap:Body><OCS xmlns="urn:OCS" action="loginRedirect" path="/Familie/"><owncloud_zimlet_password>cccccccc</owncloud_zimlet_password><owncloud_zimlet_username>ccccccccccc</owncloud_zimlet_username><owncloud_zimlet_server_name>https://host.domain.ch</owncloud_zimlet_server_name><owncloud_zimlet_server_port>443</owncloud_zimlet_server_port><owncloud_zimlet_server_path>/filedav</owncloud_zimlet_server_path><owncloud_zimlet_oc_folder>/nextcloud</owncloud_zimlet_oc_folder></OCS></soap:Body></soap:Envelope>
```

**Comment by ghost** [comment]
You did not install correctly, please re download and run the installer as in the readme. 

Restart Zimbra afterwards to be sure. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by seidler2547** [comment]
I have the same problem. I ran the installer and answered all questions correctly (I think) and it also doesn't work for me. What is OCS?

Using CentOS 7 by the way.

**Comment by moetiker** [comment]
> I have the same problem. I ran the installer and answered all questions correctly (I think) and it also doesn't work for me. What is OCS?

Own Cloud Service 

probably

**Comment by ghost** [comment]
OCS is a legacy naming. basically WebDAV Client Zimlet does all the WebDAV and the OCS component implements the API specific to Seafile or Nextcloud.

If you get the error UNKNOWN_DOCUMENT it means the jar file for OCS is not installed, possibly if you run an older version of Seafile, you will get a different error message.

**Comment by ghost** [comment]
perhaps a permission issue, can you post output of

      ls -hal /opt/zimbra/lib/ext/OCS

**Comment by seidler2547** [comment]
> ```
>   ls -hal /opt/zimbra/lib/ext/OCS
> ```

Folder doesn't exist. Other folders in ext are all owned by `root`.
