### ISSUE TITLE
"Send link(s)" doesn't work

### ISSUE THREAD

**Issue by seidler2547** [Zimbra-Community/seafile#4]
I can see the "Send Link(s)" menu item on files, but it doesn't do anything.

**Comment by ghost** [comment]
What version of Zimbra/Seafile is this, did you run the installer from:

https://github.com/Zimbra-Community/seafile  ?


Please re-run the installer, save the output and restart zimbra.

**Comment by seidler2547** [comment]
Did all that. I got some error messages about `tr`. No other significant error messages. Probably OCS isn't being installed, but I cannot see anything about that. The README said when asked about installing OCS, say yes, but the question never came.

**Comment by ghost** [comment]
Sounds like the installer did not complete, which indicates a bug can you copy paste the installer output, please re-download and re-run if you haven't saved the output.

**Comment by ghost** [comment]
I have just committed a new version of the installer that force enables the OCS component.

**Comment by seidler2547** [comment]
I see. Well, the installer question was:

> "Do you want to install public link sharing?"
> "If you use a WebDAV server that is not ownCloud or Nextcloud choose n."
> "If you have trouble or are unsure, choose Y. Y/n:"

Since I do not run ownCloud or Nextcloud, I chose `n`. Is that also the reason for #5 ?

**Comment by ghost** [comment]
Yeah it is a stupid question, I have removed it from the installer now.

**Comment by ghost** [comment]
yeah https://github.com/Zimbra-Community/seafile/issues/5   is the same problem
