### ISSUE TITLE
Feature Request: offer "Attach" as link to Seafile

### ISSUE THREAD

**Issue by seidler2547** [Zimbra-Community/seafile#5]
In an ideal Seafile+Zimbra scenario, I would want to not send out attachements at all, Ideally there should be two options:

1. offer to insert a link to a Seafile file in the current compose window
2. offer to convert "conventional" attachements to Seafile links by uploading them to a Seafile folder and creating links for them

We had used Horde Groupware before, and it offered a feature that any attachment larger than a certain size would be automatically uploaded to the Horde file store and the attachment was then replaced by a link to it. That is a great feature I think.

**Comment by ghost** [comment]
This functionality exists:

http://barrydegraaff.github.io/owncloud/attach-menu.png

**Comment by seidler2547** [comment]
> This functionality exists:
> 
> http://barrydegraaff.github.io/owncloud/attach-menu.png

But that attaches a file to the email, right? The purpose of having a central file store for us is to not send around attachments but to direct people to the file stored on the central file store server.

**Comment by ghost** [comment]
No, in the next pop-up screen you can select: Public link to file/folder then it does what you want,

![image](https://user-images.githubusercontent.com/4353213/64676693-68251180-d476-11e9-92f8-84ae589d4195.png)

**Comment by seidler2547** [comment]
![image](https://user-images.githubusercontent.com/729588/64676948-eaadd100-d476-11e9-9d47-cd4757ba87dc.png)

**Comment by ghost** [comment]
yah, ocs is not installed, re-download and re-run the installer

AND SAVE THE OUTPUT of the installer and copy paste here.

**Comment by ghost** [comment]
wget --no-cache https://raw.githubusercontent.com/Zimbra-Community/seafile/master/webdav-client-installer.sh -O /tmp/webdav-client-installer.sh
    chmod +rx /tmp/webdav-client-installer.sh
    /tmp/webdav-client-installer.sh
