### ISSUE TITLE
Seafile Zimlet for Zimbra - “Go to SeaFile” button does not work

### ISSUE THREAD

**Issue by ferrettigiulio** [Zimbra-Community/seafile#6]
I have successfully installed&set-up the zimlets and main functions properly work.
Below my Seafile Zimlet configuration:
![Seafile Configuration](https://user-images.githubusercontent.com/56824831/67197847-fc7f7e00-f3fd-11e9-9c28-7e4d44d20500.jpg)

I have the following issue.
**"Go to SeaFile" button does not work** . 
Clicking the button “Go to Seafile” results in opening a new page in the browser with URL “about:blank”.

May you fix it or suggest how to sort it out?

Thanks and regards
Giulio Ferretti

**Comment by ghost** [comment]
If you ran the installer from here: 
https://raw.githubusercontent.com/Zimbra-Community/seafile/master/webdav-client-installer.sh 
It should have set up the button to go to Seafile automatically. 

If it does not work you can alter or remove the button as described here: 
[ https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences | https://github.com/Zimbra-Community/owncloud-zimlet#configuring-preferences ] 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
